version: '3'

services:
  server:
    build:
      context: .
    container_name: proxy-checker
    restart: always
    environment:
      - TZ=Europe/Kiev
    env_file:
      - .env
    volumes:
      - ./store:/store
      - ./store/store.json:/store/store.json